# Generated by Django 4.1.3 on 2023-01-30 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Whatsapp", "0005_message_read"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
