# Generated by Django 4.1.3 on 2023-01-31 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Whatsapp", "0007_alter_message_id"),
    ]

    operations = [
        migrations.DeleteModel(name="Contact",),
    ]
